### ISSUE TITLE
Handle send transfer from URL

### ISSUE THREAD

**Issue by goga-m** [PayvoHQ/wallet#800]
Replace previous deep linking functionality with simple URL handling for send transfer.

Given a URL in the form of:
`payvo:transfer?coin=ARK&network=ark.devnet&recipient=DM7UiH4b2rW2Nv11Wu6ToiZi8MJhGCEWhP`

Pull the available information, redirect to send transfer form, and fill the form fields. 

See https://github.com/PayvoHQ/wallet/blob/master/src/app/hooks/use-deeplink.ts

**Comment by alfonsobries** [comment]
@goga-m could you give me more details on how that URL is used? 

Since seems that you no longer use electron, I'm not sure how that type of URL is going to be registered or handled

It will be something that will be redirected to something like http://payvo-wallet-url/?coin=ARK&network=ark.devnet&recipient=DM7UiH4b2rW2Nv11Wu6ToiZi8MJhGCEWhP like I only need to detect the URL query and if exists handle it?

Also, the URL doesn't need a profile id? how can I know which profile to use?

**Comment by goga-m** [comment]
@alfonsobries you can ignore the `payvo:` prefix in the URL. Yes, this issue is mostly to handle regular URLs for send transactions:
```
/transfer?coin=ARK&network=ark.devnet&recipient=DM7UiH4b2rW2Nv11Wu6ToiZi8MJhGCEWhP
```

So when this path is visited, in the welcome screen a toast is shown to the user to select a profile, and then continues to the send transfer form filliing the available data from URL query (coin, network & recipient wallet). 

All the functionality and logic (along with the checks and error messages) is already implemented here in the useDeepLink hook https://github.com/PayvoHQ/wallet/blob/master/src/app/hooks/use-deeplink.ts#L12 it just needs to be triggered here in the `useEffect` (replacing the comments) https://github.com/PayvoHQ/wallet/blob/master/src/app/hooks/use-deeplink.ts#L98

In turn, the useDeepLink hook is already called in `App.tsx` https://github.com/PayvoHQ/wallet/blob/master/src/app/App.tsx#L68 

And then it could be tested just by visiting the above URL.
